### ISSUE TITLE
[Bug]:  Checkpoint save crashes with TypeError (affects all instance types) on 3.test_cases/pytorch/FSDP

### ISSUE THREAD

**Issue by Tareqox** [awslabs/awsome-distributed-training#996]
### Prerequisites

- [x] I have searched existing issues to make sure this bug has not already been reported.
- [x] I have verified the issue against the latest `main` branch.

## Environment
- Instance type: ml.g5.12xlarge (4x NVIDIA A10G GPUs per node)
- Cluster: SageMaker HyperPod with Slurm orchestration, 2 nodes
- PyTorch version: 2.7.1+cu128 (as pinned in `src/requirements.txt`)
- Transformers: 4.53.0 (as pinned in `src/requirements.txt`)
- Model: Llama 3.2 1B (`llama3_2_1b-training.sbatch`)

### Bug Description

**File:** `src/model_utils/checkpoint.py`, line 33

**Error:**
```
TypeError: get_optimizer_state_dict() got an unexpected keyword argument 'optimizer'
```

**Cause:** The `save_checkpoint` function calls `get_optimizer_state_dict(model=model, optimizer=optimizer)` using keyword arguments. In PyTorch 2.7.1, `torch.distributed.checkpoint.state_dict.get_optimizer_state_dict` changed its signature to require positional arguments.

**Impact:** Training crashes at the first checkpoint save (step 50 by default). This affects all instance types since `requirements.txt` pins `torch==2.7.1`.

**Fix:**
```python
# Before (broken with PyTorch 2.7.1)
optimizer_state_dict = get_optimizer_state_dict(
    model=model,
    optimizer=optimizer,
)

# After (works with PyTorch 2.7.1)
optimizer_state_dict = get_optimizer_state_dict(model, optimizer)
```

Same change needed for `set_optimizer_state_dict` and `set_model_state_dict` in the `load_checkpoint` function.

### Steps to Reproduce

Run 3.test_cases/pytorch/FSDP

### Relevant Log Output

```shell

```

**Comment by jothikaaravindhan** [comment]
Hi, I’d like to work on this issue if it’s still available.

**Comment by KeitaW** [comment]
Sure @jothikaaravindhan , please go ahead. Kindly create PR with validation result :)
